# Copyright 2024 INRAE, French National Research Institute for Agriculture, Food and Environment
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import bpy
from typing import Optional
import xml.etree.ElementTree as ET
from xml.dom import minidom
import os

from . import config
from . import mesh as mesh_exporter


class GazeboIgnitionModel:
    def __init__(
        self, path: str, name: str, author: Optional[str] = None, use_absolute_path: bool = False
    ):
        self.mesh_extension = ".glb"
        self.name = name
        self.author = author or "Generated by cropcraft"
        self.sdf_filename = "model.sdf"
        self.config_filename = "model.config"
        self.use_absolute_path = use_absolute_path
        self.sdf_version = "1.7"

        self.model_path = path
        self.meshes_path = os.path.join(self.model_path, "meshes")
        self.materials_path = os.path.join(self.model_path, "materials")

        os.makedirs(self.meshes_path, exist_ok=True)
        os.makedirs(self.materials_path, exist_ok=True)

        # export sdf xml based off the scene
        self.sdf = ET.Element("sdf", attrib={"version": self.sdf_version})

        self.model = ET.SubElement(self.sdf, "model", attrib={"name": self.name})
        ET.SubElement(self.model, "static").text = "true"

    def make_uri(self, filepath: str):
        if self.use_absolute_path:
            return os.path.abspath(filepath)

        relpath = os.path.relpath(filepath, os.path.dirname(self.model_path))
        return f"model://{relpath}"

    def export_object(self, name: str, object: bpy.types.Object):
        filepath = os.path.join(self.meshes_path, name) + self.mesh_extension
        object.select_set(True)
        # mesh_exporter.export_obj(filepath + ".obj", use_selection=True)
        mesh_exporter.export_from_extension(self.mesh_extension, filepath, use_selection=True)
        object.select_set(False)
        return filepath

    def export_image(self, name: str):
        image_path = os.path.join(self.materials_path, name)

        if not os.path.exists(image_path):
            image = bpy.data.images[name]
            image.save(filepath=image_path)

    def create_sdf_link(self, object: bpy.types.Object, collision_enabled=False, retro_laser=0.0):
        mesh_path = os.path.join(self.meshes_path, object.name + self.mesh_extension)

        link = ET.SubElement(self.model, "link", attrib={"name": object.name})

        visual = ET.SubElement(link, "visual", attrib={"name": object.name})
        geometry = ET.SubElement(visual, "geometry")
        mesh = ET.SubElement(geometry, "mesh")
        ET.SubElement(mesh, "uri").text = self.make_uri(mesh_path)

        # sdf collision tags
        collision = ET.SubElement(link, "collision", attrib={"name": "collision"})
        geometry = ET.SubElement(collision, "geometry")
        mesh = ET.SubElement(geometry, "mesh")
        ET.SubElement(mesh, "uri").text = self.make_uri(mesh_path)

        surface = ET.SubElement(collision, "surface")
        contact = ET.SubElement(surface, "contact")
        if not collision_enabled:
            ET.SubElement(contact, "collide_without_contact").text = "true"
            ET.SubElement(contact, "collide_bitmask").text = "0x00"

        ET.SubElement(collision, "laser_retro").text = str(retro_laser)

    def create_config(self):
        model = ET.Element("model")
        name = ET.SubElement(model, "name")
        name.text = self.name
        version = ET.SubElement(model, "version")
        version.text = "1.0"
        sdf_tag = ET.SubElement(model, "sdf", attrib={"version": self.sdf_version})
        sdf_tag.text = self.sdf_filename

        author = ET.SubElement(model, "author")
        name = ET.SubElement(author, "name")
        name.text = self.author

        return model

    def export_field(self, field: config.Field):
        for object in bpy.data.objects:
            object.select_set(False)

        ground = bpy.data.objects["ground"]
        self.export_object("ground", ground)
        self.create_sdf_link(ground, collision_enabled=True, retro_laser=0.0)

        for index, bed in enumerate(field.beds):
            object = bpy.data.objects[bed.name]
            self.export_object(bed.name, object)
            self.create_sdf_link(object, collision_enabled=False, retro_laser=float(index + 1))

        for index, weed in enumerate(field.weeds):
            object = bpy.data.objects[weed.name]
            self.export_object(weed.name, object)
            self.create_sdf_link(object, collision_enabled=False, retro_laser=float(-index - 1))

        if field.stones is not None:
            stones = bpy.data.objects["stones"]
            self.export_object("stones", stones)
            self.create_sdf_link(stones, collision_enabled=False, retro_laser=-0.5)

    def generate_sdf(self):
        xml_string = ET.tostring(self.sdf, encoding="unicode")
        reparsed = minidom.parseString(xml_string)

        with open(os.path.join(self.model_path, self.sdf_filename), "w") as sdf_file:
            sdf_file.write(reparsed.toprettyxml(indent="  "))

    def generate_config(self):
        model = self.create_config()
        xml_string = ET.tostring(model, encoding="unicode")
        reparsed = minidom.parseString(xml_string)

        config_file = open(os.path.join(self.model_path, self.config_filename), "w")
        config_file.write(reparsed.toprettyxml(indent="  "))
        config_file.close()
