#!/usr/bin/env python3
import yaml
import click


def load_config(filename: str):
    cfg = yaml.safe_load(filename)
    return cfg


@click.command()
@click.argument('config_file', type=click.File('r'))
@click.option('-d', '--output-dir', default=None)
def main(config_file, output_dir):
    cfg = load_config(config_file)
    print(cfg)


if __name__ == '__main__':
    main()
